version: '3.8'
services:
  main:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000

  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${PROJECT_NAME}
      MYSQL_USER: ${PROJECT_NAME}_user
      MYSQL_ROOT: ${PROJECT_NAME}_root
      MYSQL_PASSWORD: ${PROJECT_NAME}_123
      MYSQL_ROOT_PASSWORD: ${PROJECT_NAME}_456
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db




